apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lalitcluster
  region: ap-south-1

nodeGroups:
   - name: lalitng1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: lalitawskey
   - name: lalitng2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: lalitawskey
 